version: 2
updates:
- package-ecosystem: gomod
  directory: "/"
  schedule:
    interval: monthly
    time: "20:00"
  open-pull-requests-limit: 10
  groups:
    aws-sdk-go-v2:
      patterns:
      - "^github.com/aws/aws-sdk-go-v2"
      update-types:
      - "minor"
      - "patch"
