name: go
on: [push]
jobs:
  test:
    name: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go:
          - '1.24'
    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0
      - uses: actions/setup-go@7a3fe6cf4cb3a834922a1244abfce67bcef6a0c5 # v6.2.0
        with:
          go-version: ${{ matrix.go }}
        id: go
      - name: build & test
        run: |
          make test
