name: go
on: [push]
jobs:
  test:
    name: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go:
          - '1.24'
    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0
      - uses: actions/setup-go@0aaccfd150d50ccaeb58ebd88d36e91967a5f35b # v5.4.0
        with:
          go-version: ${{ matrix.go }}
        id: go
      - name: build & test
        run: |
          make test
