name: go
on: [push]
jobs:
  test:
    name: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go:
          - '1.24'
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      - uses: actions/setup-go@44694675825211faa026b3c33043df3e48a5fa00 # v6.0.0
        with:
          go-version: ${{ matrix.go }}
        id: go
      - name: build & test
        run: |
          make test
