name: tagpr

on:
  push:
    branches:
      - v2

jobs:
  tagpr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0
        with:
          token: ${{ secrets.GH_PAT }}
      - uses: Songmu/tagpr@e89d37247ca73d3e5620bf074a53fbd5b39e66b0 # v1.5.1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
