name: tagpr

on:
  push:
    branches:
      - v2

jobs:
  tagpr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          token: ${{ secrets.GH_PAT }}
      - uses: Songmu/tagpr@e89d37247ca73d3e5620bf074a53fbd5b39e66b0 # v1.5.1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
